<a href="https://colab.research.google.com/github/Javachenlianghong/sprincloud-config/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

print(torch.__version__)

2.0.1+cu118


##介绍张量


In [1]:
#Scalar
scalar=torch.tensor(7)
scalar

NameError: ignored

In [ ]:
scalar.ndim

In [ ]:
scalar.item()

In [ ]:
#Vector
vector=torch.tensor([7,7])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [ ]:
# MATRIX 矩阵
MATRIX=torch.tensor([[7,8],
           [9,10]])
MATRIX

In [ ]:
MATRIX.ndim

In [ ]:
MATRIX[0]

In [ ]:
MATRIX.shape#2*2

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
          [5,8,9],
          [60,5,3]]])
TENSOR

In [ ]:
TENSOR.ndim

In [ ]:
TENSOR.shape#一个3*3的张量

## 随机张量

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.7565, 0.7861, 0.3404, 0.9319],
        [0.4032, 0.4102, 0.2377, 0.9338],
        [0.8956, 0.5227, 0.2933, 0.9410]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#创建一个和图像很像的张量或者把图片变成张量
random_image_size_tensor=torch.rand(size=(3,224,224)) #height,width,color channels(R,B,G)
random_image_size_tensor.shape,random_image_size_tensor.ndim
random_image_size_tensor

tensor([[[0.1003, 0.9145, 0.4515,  ..., 0.6585, 0.6159, 0.3863],
         [0.3369, 0.4912, 0.1085,  ..., 0.3209, 0.1268, 0.7578],
         [0.5792, 0.3681, 0.3111,  ..., 0.3172, 0.5544, 0.8283],
         ...,
         [0.0228, 0.6098, 0.6372,  ..., 0.8299, 0.1123, 0.8441],
         [0.5538, 0.1268, 0.8599,  ..., 0.4698, 0.8854, 0.4949],
         [0.5016, 0.4487, 0.7721,  ..., 0.7802, 0.9805, 0.0164]],

        [[0.1150, 0.5839, 0.2186,  ..., 0.3268, 0.7162, 0.4575],
         [0.0060, 0.3178, 0.9382,  ..., 0.5691, 0.5770, 0.7327],
         [0.0366, 0.6603, 0.4377,  ..., 0.8764, 0.5865, 0.0349],
         ...,
         [0.6519, 0.3877, 0.9177,  ..., 0.4217, 0.3291, 0.7649],
         [0.7333, 0.3204, 0.2177,  ..., 0.4951, 0.9706, 0.0048],
         [0.9425, 0.7272, 0.0459,  ..., 0.7711, 0.2734, 0.4996]],

        [[0.1581, 0.0636, 0.3895,  ..., 0.1723, 0.4484, 0.6005],
         [0.4583, 0.2101, 0.0464,  ..., 0.9393, 0.2679, 0.0461],
         [0.9246, 0.5472, 0.1702,  ..., 0.6023, 0.8586, 0.

#Zeros and ones

In [ ]:
#创建全为0的张量
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor*zeros   #张量的大小要一致

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#创建全为一的张量
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
#创建随机范围的张量
#torch.range()已经弃用，使用torch.arange()
one_to_ten=torch.arange(start=1,end=10,step=2) #start 开始 end  结束  step  步距
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
#创建一个相似的张量
ten_zeros =torch.zeros_like(input=one_to_ten) #生成形状相同的张量
ten_zeros

tensor([0, 0, 0, 0, 0])

#tensor datatypes

In [ ]:
from typing_extensions import Required
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,5.0,4.6],
              dtype=None,  #数据类型  float16 float32
              device=None, #选择设备  cpu or cuda 张量的计算要在同一设备上
              requires_grad=False)  #是否跟踪梯度
float_32_tensor

tensor([3.0000, 5.0000, 4.6000])

#张量的操作
加，减，乘，除

In [ ]:
#加
tensor=torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
#乘
tensor * 10

tensor([10, 20, 30])

In [ ]:
#并没有改变原来的值
tensor

tensor([100, 200, 300])

In [ ]:
tensor=tensor * 10
tensor

tensor([100, 200, 300])

In [ ]:
#减
tensor-10

tensor([ 90, 190, 290])

In [ ]:
#乘
torch.mul(tensor,10)
torch.add(tensor,10)

tensor([110, 210, 310])

In [ ]:
tensor

tensor([100, 200, 300])

In [ ]:
#矩阵乘法
#您可以手动进行矩阵乘法，但不建议这样做。
#内置方法更快。torch.matmul()
tensor=torch.tensor([1,2,3])
#普通乘法
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#矩阵乘法
torch.matmul(tensor,tensor)

tensor(14)

#shape errors 形状错误

In [ ]:
#矩阵相乘要是 m*p p*n的矩阵
tensor_A=torch.tensor([[1,2],
            [3,4],
            [5,6]])
tensor_B=torch.tensor([[7,8],
           [9,10],
           [11,12]])
torch.mm(tensor_A,tensor_B)  #torch.mm() ==torch.matmul()

RuntimeError: ignored

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [3]:
tensor_A=torch.tensor([[1,2],
            [3,4],
            [5,6]])
tensor_B=torch.tensor([[7,8],
           [9,10],
           [11,12]
           ])
torch.mm(tensor_A,tensor_B)  #torch.mm() ==torch.matmul()

RuntimeError: ignored

#操作的方法之一是使用转置（切换给定张量的维度）

In [8]:
tensor_B.T,tensor_B.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([3, 2]))

In [10]:
tensor_B,tensor_B.T.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([2, 3]))

In [12]:
torch.mm(tensor_A,tensor_B.T),torch.mm(tensor_A,tensor_B.T).shape

(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 torch.Size([3, 3]))

#查找最小值、最大值、平均值、总和等（聚合）

In [18]:
#创建tensor
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [15]:
#最小值
x.min(),torch.min(x)

(tensor(0), tensor(0))

In [16]:
#最大值
x.max(),torch.max(x)

(tensor(90), tensor(90))

In [23]:
#平均值  mean() 该方法的数据类型为浮点型32
x.type(torch.float32).mean(),torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [26]:
#求和
x.sum(),torch.sum(x)

(tensor(450), tensor(450))

#位置最小值/最大值

In [27]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
x.argmin()

tensor(0)

In [30]:
x[0]

tensor(0)

In [31]:
x.argmax()

tensor(9)

In [33]:
x[9]

tensor(90)

#更改张量数据类型

In [10]:
#创建张量
import torch
x=torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [13]:
# Add an extra dimension
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [11]:
# Add an extra dimension
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [15]:
z=x.view(1,10)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [17]:
#改变就会改变x，因为张量和视图共享相同的内存
z[:,0]=5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [21]:
#stack 在torch中
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])